# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

ActiveRecord::Base.transaction do
  u1 = User.create!({:user_name => "u1", :password => "111111", :email => "e1@e1.com"})
  u2 = User.create!({:user_name => "u2", :password => "111111", :email => "e2@e2.com"})
  u3 = User.create!({:user_name => "u3", :password => "111111", :email => "e3@e3.com"})
  u4 = User.create!({:user_name => "u4", :password => "111111", :email => "e4@e4.com"})
  u5 = User.create!({:user_name => "u5", :password => "111111", :email => "e5@e5.com"})
  u6 = User.create!({:user_name => "u6", :password => "111111", :email => "e6@e6.com"})
  u7 = User.create!({:user_name => "Guest", :password => "111111", :email => "Guest@guest.com"})
  u8 = User.create!({:user_name => "u8", :password => "111111", :email => "e8@e8.com"})
  u9 = User.create!({:user_name => "u9", :password => "111111", :email => "e9@e9.com"})
  u10 = User.create!({:user_name => "u10", :password => "111111", :email => "e10@e10.com"})
  u11 = User.create!({:user_name => "u11", :password => "111111", :email => "e11@e11.com"})
  u12 = User.create!({:user_name => "u12", :password => "111111", :email => "e12@e12.com"})
  u13 = User.create!({:user_name => "u13", :password => "111111", :email => "e13@e13.com"})
  u14 = User.create!({:user_name => "u14", :password => "111111", :email => "e14@e14.com"})
  u15 = User.create!({:user_name => "u15", :password => "111111", :email => "e15@e15.com"})
  u16 = User.create!({:user_name => "u16", :password => "111111", :email => "e16@e16.com"})
  u17 = User.create!({:user_name => "u17", :password => "111111", :email => "e17@e17.com"})
  u18 = User.create!({:user_name => "u18", :password => "111111", :email => "e18@e18.com"})
  u19 = User.create!({:user_name => "u19", :password => "111111", :email => "e19@e19.com"})
  u20 = User.create!({:user_name => "u20", :password => "111111", :email => "e20@e20.com"})
  u21 = User.create!({:user_name => "u21", :password => "111111", :email => "e21@e21.com"})
  u22 = User.create!({:user_name => "u22", :password => "111111", :email => "e22@e22.com"})
  u23 = User.create!({:user_name => "u23", :password => "111111", :email => "e23@e23.com"})
  u24 = User.create!({:user_name => "u24", :password => "111111", :email => "e24@e24.com"})
  u25 = User.create!({:user_name => "me", :password => "111111", :email => "sungchul_lee@yahoo.com"})
  f1 = Friendship.create!({:user_id => 1, :friend_id => 2})
  f2 = Friendship.create!({:user_id => 1, :friend_id => 3})
  f3 = Friendship.create!({:user_id => 1, :friend_id => 4})
  f4 = Friendship.create!({:user_id => 2, :friend_id => 3})
  f5 = Friendship.create!({:user_id => 2, :friend_id => 4})
  f6 = Friendship.create!({:user_id => 3, :friend_id => 4})
  f7 = Friendship.create!({:user_id => 4, :friend_id => 5})
  f8 = Friendship.create!({:user_id => 5, :friend_id => 6})
  f9 = Friendship.create!({:user_id => 6, :friend_id => 1})
  l1 = Place.create!({:place_name => "l1"})
  l2 = Place.create!({:place_name => "l2"})
  l3 = Place.create!({:place_name => "l3"})
  l4 = Place.create!({:place_name => "l4"})
  l5 = Place.create!({:place_name => "l5"})
  l6 = Place.create!({:place_name => "l6"})
  l7 = Place.create!({:place_name => "l7"})
  l8 = Place.create!({:place_name => "l8"})
  l9 = Place.create!({:place_name => "l9"})
  l10 = Place.create!({:place_name => "l10"})
  l11 = Place.create!({:place_name => "l11"})
  l12 = Place.create!({:place_name => "l12"})
  l13 = Place.create!({:place_name => "l13"})
  fl1 = FavoritePlace.create!({:place_id => 1, :user_id => 1})
  fl2 = FavoritePlace.create!({:place_id => 2, :user_id => 1})
  fl3 = FavoritePlace.create!({:place_id => 3, :user_id => 1})
  fl4 = FavoritePlace.create!({:place_id => 4, :user_id => 1})
  fl5 = FavoritePlace.create!({:place_id => 1, :user_id => 2})
  fl6 = FavoritePlace.create!({:place_id => 4, :user_id => 2})
  fl7 = FavoritePlace.create!({:place_id => 5, :user_id => 2})
  fl8 = FavoritePlace.create!({:place_id => 10, :user_id => 2})
  fl9 = FavoritePlace.create!({:place_id => 1, :user_id => 4})
  fl10 = FavoritePlace.create!({:place_id => 1, :user_id => 5})
  fl11 = FavoritePlace.create!({:place_id => 1, :user_id => 6})
  fl12 = FavoritePlace.create!({:place_id => 5, :user_id => 1})
  fl13 = FavoritePlace.create!({:place_id => 6, :user_id => 1})
end