# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

ActiveRecord::Base.transaction do
  u1 = User.create!({:user_name => "u1", :password => "111111", :email => "e1@e1.com"})
  u2 = User.create!({:user_name => "u2", :password => "111111", :email => "e2@e2.com"})
  u3 = User.create!({:user_name => "u3", :password => "111111", :email => "e3@e3.com"})
  u4 = User.create!({:user_name => "u4", :password => "111111", :email => "e4@e4.com"})
  u5 = User.create!({:user_name => "u5", :password => "111111", :email => "e5@e5.com"})
  u6 = User.create!({:user_name => "u6", :password => "111111", :email => "e6@e6.com"})
  u7 = User.create!({:user_name => "Guest", :password => "111111", :email => "Guest@guest.com"})
  u8 = User.create!({:user_name => "u8", :password => "111111", :email => "e8@e8.com"})
  u9 = User.create!({:user_name => "u9", :password => "111111", :email => "e9@e9.com"})
  u10 = User.create!({:user_name => "u10", :password => "111111", :email => "e10@e10.com"})
  u11 = User.create!({:user_name => "u11", :password => "111111", :email => "e11@e11.com"})
  u12 = User.create!({:user_name => "u12", :password => "111111", :email => "e12@e12.com"})
  u13 = User.create!({:user_name => "u13", :password => "111111", :email => "e13@e13.com"})
  u14 = User.create!({:user_name => "u14", :password => "111111", :email => "e14@e14.com"})
  u15 = User.create!({:user_name => "u15", :password => "111111", :email => "e15@e15.com"})
  u16 = User.create!({:user_name => "u16", :password => "111111", :email => "e16@e16.com"})
  u17 = User.create!({:user_name => "u17", :password => "111111", :email => "e17@e17.com"})
  u18 = User.create!({:user_name => "u18", :password => "111111", :email => "e18@e18.com"})
  u19 = User.create!({:user_name => "u19", :password => "111111", :email => "e19@e19.com"})
  u20 = User.create!({:user_name => "u20", :password => "111111", :email => "e20@e20.com"})
  u21 = User.create!({:user_name => "u21", :password => "111111", :email => "e21@e21.com"})
  u22 = User.create!({:user_name => "u22", :password => "111111", :email => "e22@e22.com"})
  u23 = User.create!({:user_name => "u23", :password => "111111", :email => "e23@e23.com"})
  u24 = User.create!({:user_name => "u24", :password => "111111", :email => "e24@e24.com"})
  u25 = User.create!({:user_name => "me", :password => "111111", :email => "sungchul_lee@yahoo.com"})
  f1 = Friendship.create!({:user_id => 1, :friend_id => 2})
  f2 = Friendship.create!({:user_id => 1, :friend_id => 3})
  f3 = Friendship.create!({:user_id => 1, :friend_id => 4})
  f4 = Friendship.create!({:user_id => 2, :friend_id => 3})
  f5 = Friendship.create!({:user_id => 2, :friend_id => 4})
  f6 = Friendship.create!({:user_id => 3, :friend_id => 4})
  f7 = Friendship.create!({:user_id => 4, :friend_id => 5})
  f8 = Friendship.create!({:user_id => 5, :friend_id => 6})
  f9 = Friendship.create!({:user_id => 6, :friend_id => 1})
  # fg1 = FriendGroup.create!({:group_name => "g1", :owner_id => 1})
#   fg2 = FriendGroup.create!({:group_name => "g2", :owner_id => 1})
#   fg3 = FriendGroup.create!({:group_name => "g3", :owner_id => 1})
#   fg4 = FriendGroup.create!({:group_name => "g1", :owner_id => 2})
#   fg5 = FriendGroup.create!({:group_name => "g2", :owner_id => 2})
#   fg6 = FriendGroup.create!({:group_name => "g4", :owner_id => 2})
#   fg7 = FriendGroup.create!({:group_name => "g5", :owner_id => 3})
#   fg8 = FriendGroup.create!({:group_name => "g6", :owner_id => 4})
#   fg9 = FriendGroup.create!({:group_name => "g7", :owner_id => 5})
  e1 = Event.create!({:title => "e1", :creator_id => 1})
  e2 = Event.create!({:title => "e2", :creator_id => 1})
  e3 = Event.create!({:title => "e3", :creator_id => 1})
  e4 = Event.create!({:title => "e1", :creator_id => 2})
  e5 = Event.create!({:title => "e1", :creator_id => 2})
  e6 = Event.create!({:title => "e1", :creator_id => 3})
  e7 = Event.create!({:title => "e3", :creator_id => 3})
  e8 = Event.create!({:title => "e2", :creator_id => 4})
  e9 = Event.create!({:title => "e2", :creator_id => 5})
  e10 = Event.create!({:title => "e1", :creator_id => 6})
  e11 = Event.create!({:title => "e1", :creator_id => 6})
  ec1 = EventCircle.create!({:user_id => 1, :event_id => 1})
  ec2 = EventCircle.create!({:user_id => 1, :event_id => 2})
  ec3 = EventCircle.create!({:user_id => 1, :event_id => 3})
  ec4 = EventCircle.create!({:user_id => 1, :event_id => 4})
  ec5 = EventCircle.create!({:user_id => 2, :event_id => 4})
  ec6 = EventCircle.create!({:user_id => 3, :event_id => 2})
  ec7 = EventCircle.create!({:user_id => 3, :event_id => 1})
  ec8 = EventCircle.create!({:user_id => 4, :event_id => 1})
  ec9 = EventCircle.create!({:user_id => 5, :event_id => 1})
  ec10 = EventCircle.create!({:user_id => 6, :event_id => 1})
  l1 = Place.create!({:place_name => "l1"})
  l2 = Place.create!({:place_name => "l2"})
  l3 = Place.create!({:place_name => "l3"})
  l4 = Place.create!({:place_name => "l4"})
  l5 = Place.create!({:place_name => "l5"})
  l6 = Place.create!({:place_name => "l6"})
  l7 = Place.create!({:place_name => "l7"})
  l8 = Place.create!({:place_name => "l8"})
  l9 = Place.create!({:place_name => "l9"})
  l10 = Place.create!({:place_name => "l10"})
  l11 = Place.create!({:place_name => "l11"})
  l12 = Place.create!({:place_name => "l12"})
  l13 = Place.create!({:place_name => "l13"})
  # a1 = Address.create!({:place_id => 1, :address1 => "1 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11111"})
#   a2 = Address.create!({:place_id => 2, :address1 => "2 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11112"})
#   a3 = Address.create!({:place_id => 3, :address1 => "3 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11113"})
#   a4 = Address.create!({:place_id => 4, :address1 => "4 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11114"})
#   a5 = Address.create!({:place_id => 5, :address1 => "5 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11115"})
#   a6 = Address.create!({:place_id => 6, :address1 => "6 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11116"})
#   a7 = Address.create!({:place_id => 7, :address1 => "7 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11117"})
#   a8 = Address.create!({:place_id => 8, :address1 => "8 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11118"})
#   a9 = Address.create!({:place_id => 9, :address1 => "9 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11119"})
#   a10 = Address.create!({:place_id => 10, :address1 => "10 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11110"})
#   a11 = Address.create!({:place_id => 11, :address1 => "11 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11111"})
#   a12 = Address.create!({:place_id => 12, :address1 => "12 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11112"})
#   a13 = Address.create!({:place_id => 13, :address1 => "13 street", :address2 => "blank", :city => "sf", :state => "ca", :zip =>"11113"})
  fl1 = FavoritePlace.create!({:place_id => 1, :user_id => 1})
  fl2 = FavoritePlace.create!({:place_id => 2, :user_id => 1})
  fl3 = FavoritePlace.create!({:place_id => 3, :user_id => 1})
  fl4 = FavoritePlace.create!({:place_id => 4, :user_id => 1})
  fl5 = FavoritePlace.create!({:place_id => 1, :user_id => 2})
  fl6 = FavoritePlace.create!({:place_id => 4, :user_id => 2})
  fl7 = FavoritePlace.create!({:place_id => 5, :user_id => 2})
  fl8 = FavoritePlace.create!({:place_id => 10, :user_id => 2})
  fl9 = FavoritePlace.create!({:place_id => 1, :user_id => 4})
  fl10 = FavoritePlace.create!({:place_id => 1, :user_id => 5})
  fl11 = FavoritePlace.create!({:place_id => 1, :user_id => 6})
  fl12 = FavoritePlace.create!({:place_id => 5, :user_id => 1})
  fl13 = FavoritePlace.create!({:place_id => 6, :user_id => 1})
  # fgc1 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 2})
 #  fgc2 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 3})
 #  fgc3 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 4})
 #  fgc4 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 5})
 #  fgc5 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 6})
 #  fgc6 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 7})
 #  fgc7 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 8})
 #  fgc8 = FriendGroupCircle.create!({:friend_group_id => 1, :user_id => 9})
 #  fgc9 = FriendGroupCircle.create!({:friend_group_id => 2, :user_id => 3})
 #  fgc10 = FriendGroupCircle.create!({:friend_group_id => 2, :user_id => 4})
 #  fgc11 = FriendGroupCircle.create!({:friend_group_id => 2, :user_id => 3})
 #  fgc12 = FriendGroupCircle.create!({:friend_group_id => 3, :user_id => 1})
 #  fgc13 = FriendGroupCircle.create!({:friend_group_id => 3, :user_id => 2})
 #  fgc14 = FriendGroupCircle.create!({:friend_group_id => 4, :user_id => 3})
 #  fgc15 = FriendGroupCircle.create!({:friend_group_id => 5, :user_id => 2})
 #  fgc16= FriendGroupCircle.create!({:friend_group_id => 6, :user_id => 2})

end